# Generated by Django 5.0.6 on 2024-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('conversasion', models.JSONField()),
                ('update_date', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_language', models.CharField(blank=True, choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol')], max_length=2, null=True)),
                ('default_timezone', models.CharField(blank=True, choices=[('UTC', 'UTC'), ('America/Sao_Paulo', 'America/Sao_Paulo')], max_length=50, null=True)),
                ('whatsapp_business_api_token', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_business_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(default=1)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_context', to='chat.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('events', models.JSONField(blank=True, null=True)),
                ('training_phrases', models.JSONField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_intent', to='chat.agent')),
                ('input_contexts', models.ManyToManyField(blank=True, related_name='intents_input', to='chat.context')),
                ('output_contexts', models.ManyToManyField(blank=True, related_name='intents_output', to='chat.context')),
            ],
        ),
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('required', models.BooleanField(default=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('entity', models.CharField(choices=[('', 'Required'), ('OPTIONAL', 'Optional')], max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('is_list', models.BooleanField(default=False)),
                ('prompts', models.TextField(blank=True, null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_parameters_set', to='chat.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Session_historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_ip', models.CharField(max_length=100)),
                ('context', models.JSONField(default=list)),
                ('input', models.TextField(blank=True)),
                ('executing_action', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('closed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.agent')),
                ('current_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session_historic')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('base_auth_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_auth_password', models.CharField(blank=True, max_length=100, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('in_line', models.TextField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='chat.agent')),
            ],
        ),
        migrations.AddField(
            model_name='intent',
            name='fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents_fulfillment', to='chat.webhook'),
        ),
    ]
