# Generated by Django 5.0.4 on 2024-04-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('entity', models.CharField(choices=[('', 'Required'), ('OPTIONAL', 'Optional')], max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('is_list', models.BooleanField(default=False)),
                ('prompts', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('events', models.JSONField(blank=True, null=True)),
                ('training_phrases', models.JSONField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('action_parameters', models.ManyToManyField(related_name='intents', to='chat.actionparameter')),
                ('input_contexts', models.ManyToManyField(blank=True, related_name='intents_input', to='chat.context')),
                ('output_contexts', models.ManyToManyField(blank=True, related_name='intents_output', to='chat.context')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_language', models.CharField(blank=True, choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol')], max_length=2, null=True)),
                ('default_timezone', models.CharField(blank=True, choices=[('UTC', 'UTC'), ('America/Sao_Paulo', 'America/Sao_Paulo')], max_length=50, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('intents', models.ManyToManyField(blank=True, related_name='agents', to='chat.intent')),
            ],
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_parameters_set', to='chat.intent'),
        ),
    ]
