# Generated by Django 5.0.4 on 2024-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
