# Generated by Django 5.0.4 on 2024-04-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
