# Generated by Django 5.0.4 on 2024-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_actionparameter_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intent',
            name='action_parameters',
        ),
        migrations.AlterField(
            model_name='agent',
            name='intents',
            field=models.ManyToManyField(blank=True, related_name='intents', to='chat.intent'),
        ),
    ]
