# Generated by Django 5.0.4 on 2024-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_intent_action_parameters_alter_agent_intents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('conversasion', models.JSONField()),
                ('update_date', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
