# Generated by Django 5.0.4 on 2024-05-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='intents',
        ),
        migrations.AddField(
            model_name='agent',
            name='intents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_intents', to='chat.intent'),
        ),
    ]
