# Generated by Django 5.0.4 on 2024-05-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_agent_intents_agent_intents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='intents',
        ),
        migrations.AddField(
            model_name='intent',
            name='intents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='chat.agent'),
        ),
    ]
