# Generated by Django 5.0.4 on 2024-05-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_agent_intents_intent_intents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intent',
            name='intents',
        ),
        migrations.AddField(
            model_name='context',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_context', to='chat.agent'),
        ),
        migrations.AddField(
            model_name='intent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_intent', to='chat.agent'),
        ),
    ]
